---
name: CI
on: [push]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.15', '1.16', '1.17']
    runs-on: ${{ matrix.os }}
    name: Test go${{ matrix.go }}-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go mod tidy
      - run: go build